distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.0.14
install_time: "Thu Jul 28 00:43:58 2022"
installation_id: "71e2347e-a828-4e4e-8565-f7d7e8f08d57"
rime_version: 1.7.3